server:
  port: 80
  error.include-message: always
spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: ${DATABASE_URI}
      uri: ${DATABASE_URI}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
management:
  health.enabled: true

